-- AlterTable
ALTER TABLE "FLOEntity" ALTER COLUMN "cert_body" SET DATA TYPE VARCHAR(300),
ALTER COLUMN "cert_status" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "lic_body" SET DATA TYPE VARCHAR(300),
ALTER COLUMN "lic_status" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "op_address" SET DATA TYPE VARCHAR(500),
ALTER COLUMN "op_countryCode" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "op_name" SET DATA TYPE VARCHAR(400),
ALTER COLUMN "op_region" SET DATA TYPE VARCHAR(300),
ALTER COLUMN "op_subregion" SET DATA TYPE VARCHAR(300);
